# Generated by Django 5.2.4 on 2025-07-19 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='estendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='prazo_final',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 6, 7, 52, 482553, tzinfo=datetime.timezone.utc)),
        ),
    ]
