# Generated by Django 5.2.4 on 2025-07-19 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_emprestimo_estendido_emprestimo_prazo_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='prazo_final',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 6, 9, 48, 256508, tzinfo=datetime.timezone.utc)),
        ),
    ]
