# Generated by Django 5.2.4 on 2025-07-19 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_emprestimo_prazo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='prazo_final',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 6, 40, 3, 265063, tzinfo=datetime.timezone.utc)),
        ),
    ]
