# Generated by Django 5.2.4 on 2025-07-20 05:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_emprestimo_prazo_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='estendido',
            new_name='prazo_estendido',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='prazo_final',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 27, 5, 51, 10, 99013, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
