# Generated by Django 5.2.4 on 2025-07-20 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_rename_prazo_estendido_emprestimo_estendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='prazo_final',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 19, 5, 56, 55, 532422, tzinfo=datetime.timezone.utc)),
        ),
    ]
