# Generated by Django 5.2.4 on 2025-07-20 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_remove_emprestimo_estendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 27, 6, 4, 18, 105330, tzinfo=datetime.timezone.utc)),
        ),
    ]
