# Generated by Django 5.2.4 on 2025-07-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_alter_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
    ]
