# Generated by Django 5.2.4 on 2025-07-20 18:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_remove_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='prazo_estendido',
            new_name='estendido',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='prazo_final',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 19, 18, 44, 57, 363332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario'),
        ),
    ]
