# Generated by Django 5.2.4 on 2025-07-20 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_rename_prazo_estendido_emprestimo_estendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='prazo_final',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 19, 18, 51, 40, 462924, tzinfo=datetime.timezone.utc)),
        ),
    ]
